### ISSUE TITLE
Issue Identifying Group Search String from M3u.

### ISSUE THREAD

**Issue by SimoneGold** [haxcop/AutomatedHMS#4]
I am having issues getting the script to work with non-Vaders m3u. It seems to fail with the grouping. I am entering the correct group for listed in my m3u link, but the script seems to look for a specific search string like "group". Mine is listed is "group-title", so I think it causes it to fail because of the search string doesn't match.

Can you please test with other services other than Vaders? Thanks!

**Comment by haxcop** [comment]
@SimoneGold Hi In order for me to test with other providers i need the provider details. and currently i do not have others. 
even though the Vaders m3u looks into any details including "group-title" too - so in that case you need to use the exact name for the desired group found in your file.
example group-title "USA" - you will type `'usa'` (notice it must be lowercase Always)
